server:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    hosts:
      - host: vault.sayzx.fr
        paths:
          - /
    tls:
      - secretName: vault-tls
        hosts:
          - vault.sayzx.fr
  dataStorage:
    enabled: true
    size: 5Gi
ui:
  enabled: true